### ISSUE TITLE
Prebuild.js

### ISSUE THREAD

**Issue by KHYehor** [oknosoft/metadata.js#436]
Добрый день!

Выполнил последовательно пункты из данной инструкции https://infostart.ru/public/540168/ ШАГ5, на момента где я ввожу команду `gulp full`
у меня вылетает такое вот исключение,
```
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Applications/github/testapp/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Applications/github/testapp/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Applications/github/testapp/gulpfile.js:91:6)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at execute (/Users/ykh2k/.nvm/versions/node/v11.15.0/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
```

посмотрев содержимое файла `gulpfile.js` на 91ой строке, путем исключения понял, что проблема в вашем `prebuild.js`

**Comment by KHYehor** [comment]
Мы скормили данные meta данные из демоверсии.

**Comment by unpete** [comment]
Инструкция безнадежно устарела.
Gulp для сборки пару лет, как не используем.
Helloworld должен работать. Недавно тестировали  Если что-то не собирается, проверяйте версии зависимостей.

**Comment by nosovk** [comment]
А где взять актуальную версию?

**Comment by nosovk** [comment]
Я как бы тоже за вебпак, но prebuild из couchdb забирает meta и из него генерирует обьекты. Мы к вебпаку его прикрутить не сможем малой кровью

**Comment by nosovk** [comment]
И мы смотрели `metadata init`

**Comment by unpete** [comment]
metadata init - это v0.12. Его похоронили 3 года назад. См. https://github.com/oknosoft/helloworld
